### ISSUE TITLE
Showing an error message when adding a new node from the SDF menu

### ISSUE THREAD

**Issue by bhrgvrm** [williamchange/b3dsdf#5]
```
Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\b3dsdf\__init__.py", line 185, in invoke
    return self.execute(context)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\b3dsdf\__init__.py", line 159, in execute
    raise FileNotFoundError("No .blend File in directory " + dir_path)
FileNotFoundError: No .blend File in directory C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\b3dsdf
```
It is happening though I put the given `sdf_nodegroups.blend` to the defined assets directory.

**Comment by williamchange** [comment]
You don't need to move the .blend file if you are using the addon directly
